In [12]:
pip install pyodbc

Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
import pyodbc

In [2]:
df = pd.read_excel('Nashville_Housing.xlsx')
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [3]:
server = 'SQL/ServerName'
database = 'DataBaseName'
user = 'User Name'
password = 'Password'

# Define the connection string for SQL Server
connection_str = f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={user};PWD={password}'

In [4]:
connection_str = f'mssql+pyodbc://{user}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'

try:
    engine = create_engine(connection_str)
    
    df.to_sql(name = 'Nashville_Housing', con = engine, if_exists = 'replace', index = False)
    
    print("Data export to SQL Server database is successful")
except Exception as e:
    print("Error connecting to SQL Server database: ", str(e))

Data export to SQL Server database is successful

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  int64
 1   ParcelID         56477 non-null  object
 2   LandUse          56477 non-null  object
 3   PropertyAddress  56448 non-null  object
 4   SaleDate         56477 non-null  datetime64[ns]
 5   SalePrice        56477 non-null  int64
 6   LegalReference   56477 non-null  object
 7   SoldAsVacant     56477 non-null  object
 8   OwnerName        25261 non-null  object
 9   OwnerAddress     26015 non-null  object
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  object
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(8)
memory usage: 8.2+ MB